# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PracticeInfo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepting_clients",
                    models.BooleanField(
                        default=False,
                        help_text="This affects the text displayed on the 'Hours and Area' page.",
                        verbose_name="accepting new clients",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, default="", verbose_name="practice address"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="practice email",
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=17,
                        verbose_name="practice fax number",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=17,
                        verbose_name="practice phone number",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
