# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceinfo',
            name='accepting_clients_text',
            field=models.TextField(blank=True, default='', help_text="This text is displayed on the 'Hours and Area' page when 'Accepting new clients' is checked.", verbose_name='accepting new clients message'),
        ),
        migrations.AddField(
            model_name='practiceinfo',
            name='not_accepting_clients_text',
            field=models.TextField(blank=True, default='', help_text="This text is displayed on the 'Hours and Area' page when 'Accepting new clients' is <strong>not</strong> checked.", verbose_name='not accepting new clients message'),
        ),
    ]
