# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration", "0002_auto_20161024_1842"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practiceinfo",
            options={"verbose_name": "practice information"},
        ),
    ]
