# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="picture_height",
            field=models.IntegerField(
                default=0, verbose_name="picture height"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="picture_width",
            field=models.IntegerField(default=0, verbose_name="picture width"),
            preserve_default=False,
        ),
    ]
