# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_auto_20161006_0355"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ("first_name", "last_name")},
        ),
        migrations.AddField(
            model_name="patient",
            name="first_letter",
            field=models.CharField(
                default="B", max_length=1, verbose_name="first letter"
            ),
            preserve_default=False,
        ),
    ]
