# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20161006_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='featured',
            field=models.BooleanField(default=False, help_text='Patients marked as featured will be displayed on the gallery home page.', verbose_name='featured'),
        ),
    ]
