# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_patient_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="thumbnail",
            field=models.ImageField(
                height_field="thumbnail_height",
                null=True,
                upload_to=gallery.models.patient_thumbnail_path,
                verbose_name="picture thumbnail",
                width_field="thumbnail_width",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="thumbnail_height",
            field=models.IntegerField(
                null=True, verbose_name="picture thumbnail height"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="thumbnail_width",
            field=models.IntegerField(
                null=True, verbose_name="picture thumbnail width"
            ),
        ),
    ]
