# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_patient_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="picture_height",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="picture_width",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="thumbnail_height",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="thumbnail_width",
        ),
        migrations.AlterField(
            model_name="patient",
            name="picture",
            field=models.ImageField(
                upload_to=gallery.models.patient_image_path,
                verbose_name="picture",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="thumbnail",
            field=models.ImageField(
                null=True,
                upload_to=gallery.models.patient_thumbnail_path,
                verbose_name="picture thumbnail",
            ),
        ),
    ]
