# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20170318_2037'),
        ('gallery', '0007_auto_20161101_1921'),
    ]

    operations = [
    ]
