# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='biography')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=team.models.team_member_image_name)),
            ],
        ),
    ]
