# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 23:41
from __future__ import unicode_literals

from django.db import migrations


def preset_order(apps, schema_editor):
    """Make sure each team member has an order value"""
    TeamMember = apps.get_model("team", "TeamMember")

    for i, member in enumerate(TeamMember.objects.all()):
        member.order = i + 1
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_auto_20161024_2338"),
    ]

    operations = [
        migrations.RunPython(preset_order, migrations.RunPython.noop),
    ]
