# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone number')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('url', models.URLField(blank=True, verbose_name='website URL')),
            ],
        ),
    ]
