# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_auto_20161018_1847"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="important",
            field=models.BooleanField(
                default=False,
                help_text="Categories marked important will be shown at the top of the resource list",
                verbose_name="important",
            ),
        ),
    ]
