# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='important',
            field=models.BooleanField(default=False, help_text=('categories marked important will be shown at the top of ', 'the resource list'), verbose_name='important'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='title'),
        ),
    ]
