name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tag
        run: echo "IMAGE_TAG=$(date +%Y-%m-%d-%s)-${{ github.sha }}" >> ${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chmvh/web:latest,chmvh/web:${{ env.IMAGE_TAG }}
